In [2]:
import torch
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [3]:
x.dtype

torch.int64

### neural network creation using NN

In [4]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

### Generate Dataset

In [5]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.3016],
        [0.3049],
        [0.3035],
        [0.3054],
        [0.3123],
        [0.2786],
        [0.3017],
        [0.2835],
        [0.3034],
        [0.3006]], grad_fn=<SigmoidBackward0>)

In [6]:
import numpy as np
import pandas as pd
import torch

In [7]:
df = pd.read_csv("/Users/dhrutamacm2/Desktop/PyToarch/data.csv")
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
114,864496,B,8.726,15.83,55.84,230.9,0.11500,0.08201,0.04132,0.01924,...,19.62,64.48,284.4,0.1724,0.23640,0.2456,0.10500,0.2926,0.10170,NaN
393,903516,M,21.610,22.28,144.40,1407.0,0.11670,0.20870,0.28100,0.15620,...,28.74,172.00,2081.0,0.1502,0.57170,0.7053,0.24220,0.3828,0.10070,NaN
96,86211,B,12.180,17.84,77.79,451.1,0.10450,0.07057,0.02490,0.02941,...,20.92,82.14,495.2,0.1140,0.09358,0.0498,0.05882,0.2227,0.07376,NaN
318,894329,B,9.042,18.90,60.07,244.5,0.09968,0.19720,0.19750,0.04908,...,23.40,68.62,297.1,0.1221,0.37480,0.4609,0.11450,0.3135,0.10550,NaN
481,91227,B,13.900,19.24,88.73,602.9,0.07991,0.05326,0.02995,0.02070,...,26.42,104.40,830.5,0.1064,0.14150,0.1673,0.08150,0.2356,0.07603,NaN

In [8]:
df = df.drop(columns=["id","Unnamed: 32"])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [9]:
x = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder = LabelEncoder()
y_scaled = encoder.fit_transform(y)
y_scaled

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [12]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled,y_scaled,test_size=0.2, random_state=42)

In [20]:
x_train_tensor = torch.tensor(x_train, dtype=torch.float)
y_train_tensor = torch.tensor(y_train, dtype=torch.float).unsqueeze(1)
x_test_tensor = torch.tensor(x_test, dtype=torch.float)
y_test_tensor = torch.tensor(y_test, dtype=torch.float).unsqueeze(1)

In [21]:
x_train_tensor.shape

torch.Size([455, 30])

In [22]:
y_train_tensor.shape

torch.Size([455, 1])

### define model

##### num_features → how many inputs the model expects 
##### features → the actual input data given to the model

In [27]:
import torch.nn as nn

class simpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self, features):
        out = self.network(features)
        return out

In [28]:
learning_reate = 0.1
epochs = 25

In [29]:
model = simpleNN(x_train_tensor.shape[1])
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_reate)

In [31]:
# create model
model = simpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_reate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(x_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor)

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6729225516319275
Epoch: 2, Loss: 0.6558237075805664
Epoch: 3, Loss: 0.640895426273346
Epoch: 4, Loss: 0.6270581483840942
Epoch: 5, Loss: 0.6139234900474548
Epoch: 6, Loss: 0.6001853942871094
Epoch: 7, Loss: 0.586631178855896
Epoch: 8, Loss: 0.5724332332611084
Epoch: 9, Loss: 0.5573927760124207
Epoch: 10, Loss: 0.5411738753318787
Epoch: 11, Loss: 0.5245767831802368
Epoch: 12, Loss: 0.507422924041748
Epoch: 13, Loss: 0.48958685994148254
Epoch: 14, Loss: 0.4714099168777466
Epoch: 15, Loss: 0.4536101222038269
Epoch: 16, Loss: 0.4360908269882202
Epoch: 17, Loss: 0.418862521648407
Epoch: 18, Loss: 0.4024430811405182
Epoch: 19, Loss: 0.3867243528366089
Epoch: 20, Loss: 0.37184494733810425
Epoch: 21, Loss: 0.3578520715236664
Epoch: 22, Loss: 0.3445698022842407
Epoch: 23, Loss: 0.33194777369499207
Epoch: 24, Loss: 0.31993427872657776
Epoch: 25, Loss: 0.3085923194885254